.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. eclipt_qt test_eclipt_qt
clean: FORCE
	$(MAKE) -C .. eclipt_qt_clean test_eclipt_qt_clean
check: FORCE
	$(MAKE) -C .. test_eclipt_qt_check
eclipt-qt eclipt-qt.exe: FORCE
	 $(MAKE) -C .. eclipt_qt
